workflows:
  android-release-workflow:
    name: Android Release Build
    max_build_duration: 60
    environment:
      groups:
        - google_play_api  # Zde voláme naši novou skupinu s JSON klíčem
      android_signing:
        - sudokukey
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - name: Sestaveni Android App Bundle pro Google Play
        script: |
          chmod +x ./gradlew
          ./gradlew bundleRelease -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GPLAY_JSON
        track: production
        in_app_update_priority: 0