workflows:
  android-release-workflow:
    name: Android Release Build
    max_build_duration: 60
    environment:
      android_signing:
        - sudokukey
    scripts:
      - name: Sestaveni Android App Bundle pro Google Play
        script: |
          chmod +x ./gradlew
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/bundle/release/*.aab